import { C8oLogLevel } from "./c8oLogLevel";
export declare class C8oBase {
    protected _endpointSettings: string;
    protected _timeout: number;
    protected _cookies: Object;
    protected _clientCertificateFiles: Object;
    protected _clientCertificateBinaries: Object;
    protected _logRemote: boolean;
    protected _initialLogRemote: boolean;
    protected _logLevelLocal: C8oLogLevel;
    protected _logC8o: boolean;
    protected _logOnFail: (exception: Error, parameters: Object) => void;
    protected _defaultDatabaseName: string;
    protected _authenticationCookieValue: string;
    protected _fullSyncLocalSuffix: string;
    protected _fullSyncServerUrl: string;
    protected _fullSyncUsername: string;
    protected _fullSyncPassword: string;
    protected _useEncryption: boolean;
    protected _disableSSL: boolean;
    protected _keyStorePassword: string;
    protected _trustStorePassword: string;
    protected _headers: Object;
    readonly timeout: number;
    readonly cookies: Object;
    readonly logRemote: boolean;
    readonly logLevelLocal: C8oLogLevel;
    readonly logC8o: boolean;
    readonly defaultDatabaseName: string;
    readonly authenticationCookieValue: string;
    readonly fullSyncLocalSuffix: string;
    readonly fullSyncServerUrl: string;
    readonly fullSyncUsername: string;
    readonly fullSyncPassword: string;
    readonly logOnFail: (exception: Error, parameters: Object) => void;
    readonly endpoint: string;
    readonly headers: Object;
    copy(c8oBase: C8oBase): void;
}
