/**
 * Flowtype definitions for c8oLogLev
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export class C8oLogLevel {
    NULL: C8oLogLevel;
    NONE: C8oLogLevel;
    TRACE: C8oLogLevel;
    DEBUG: C8oLogLevel;
    INFO: C8oLogLevel;
    WARN: C8oLogLevel;
    ERROR: C8oLogLevel;
    FATAL: C8oLogLevel;
    C8O_LOG_LEVELS: ;
    name: string;
    priority: number;
    constructor(name: string, priority: number): this;
    getC8oLogLevel(name: string): C8oLogLevel
}