/**
 * Flowtype definitions for c8oPromi
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare export class C8oPromise<T>{
    constructor(c8o: C8o): this;
    async (): Promise<any>;
    then(c8oOnResponse: (response: T, parameters: Object) => C8oPromise<T>): void;
    progress(c8oOnProgress: (C8oProgress: any) => C8oPromise<T>): void;
    fail(c8oOnFail: (error: Error, parameters: Object) => C8oPromise<T>): void;
    onResponse(response: T, parameters: Object): void;
    onProgress(progress: any): void;
    onFailure(error: Error, parameters: Object): void
}